### ISSUE TITLE
Not compatiable for the latest userdefinedform module

### ISSUE THREAD

**Issue by sparkcom** [webfox/silverstripe-userforms-mailchimp#6]
Hello, 
wonder if there is any plan to make it compatible with the latest version of userdefinedform module? 

many thanks!!

**Comment by hailwood** [comment]
Hey @sparkcom ,

As far as I know this is fixed but we forgot to close the issue.

Let me know if that's not the case!

**Comment by asecondwill** [comment]
This isn't working for me. 

"silverstripe/cms": "3.5.0",
"silverstripe/userforms": "3.1.1",
"webfox/silverstripe-userforms-mailchimp": "^1.1"

I can add a field and change it to "Mailchimp Subscription Field" but there are no settings for mailchimp list of fields. 

my config.yml has:

````
EditableMailchimpSubscribeField:
  api_key: '149a4d2eaa48f4e1ec5539e1ecda13e5-us1'
````

and i've dev/build and ?flush=all  to no avail.  

Looks like a great idea for a module.  any help would be awesome.
